src/CouronneAPI/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CouronneAPI.Models
{
    public class Game
    {

        public int Id { get; set; }
        [Required]
        public int Player1 { get; set; }
        [Required]
        public int Player2 { get; set; }
        [Required]
        public int Winner { get; set; }
        public DateTime PlayDate { get; set; }
    }
}

src/CouronneAPI/Models/Player.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CouronneAPI.Models
{
    public class Player
    {
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string UserName { get; set; }
        public DateTime Created { get; set; }
        public List<Game> Games { get; set; }
        public int Wins { get; set; }
    }
}

src/CouronneAPI/Controllers/GameController.cs
using System;
using CouronneAPI.Repositories.Interfaces;
using Microsoft.AspNet.Mvc;

// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CouronneAPI.Controllers
{
    [Route("api/[controller]")]
    public class GameController : Controller
    {
        [FromServices]
        public ICouronneRepository CouronneRepository { get; set; }


        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("create")]
        public ActionResult CreateGame(int player1, int player2)
        {
            return CouronneRepository.CreateGame(player1, player2) == 1
                ? (ActionResult) new HttpOkResult()
                : HttpBadRequest();
        }

        [HttpPost]
        [Route("setwinner")]
        public ActionResult SetWinner(int player, int gameId)
        {
            return CouronneRepository.SetWinner(player, gameId) == 1
             ? (ActionResult)new HttpOkResult() 
             : HttpBadRequest();
        }
    }
    
}

src/CouronneAPI/Controllers/PlayerController.cs
using System.Collections.Generic;
using CouronneAPI.Models;
using CouronneAPI.Repositories.Interfaces;
using Microsoft.AspNet.Mvc;



namespace CouronneAPI.Controllers
{
    [Route("api/[controller]")]
    public class PlayerController : Controller
    {
        [FromServices]
        public ICouronneRepository CouronneRepository { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        [Route("create")]
        [HttpPost]
        public ActionResult CreatePlayer(Player player)
        {
            if (!CouronneRepository.CheckUsernameExist(player.UserName))
            {

                return CouronneRepository.CreatePlayer(player) == 1
                    ? (ActionResult) new HttpOkResult()
                    : HttpBadRequest();
            }
            else
            {
                return HttpBadRequest();
            }

        }


        [Route("getplayerbyid")]
        [HttpGet]
        public Player GetPlayersById(int id)
        {
            return CouronneRepository.GetPlayer(id);
        }

        [Route("checkusername")]
        [HttpGet]
        public bool GetPlayersById(string username)
        {
            return CouronneRepository.CheckUsernameExist(username);
        }


        [Route("gethighscorelist")]
        [HttpGet]
        public IEnumerable<Player> GetPlayersByScore()
        {
            return CouronneRepository.GetHighscoreList();
        }

        [Route("gethighscorelistbymonth")]
        [HttpGet]
        public IEnumerable<Player> GetPlayersByScoreAndMonth(int month)
        {
            return CouronneRepository.GetHighscoreListByMonth(month);
        }
    }
}

src/CouronneAPI/Views/Game/Index.cshtml
@model CouronneAPI.Models.Game
@{
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head id="Head1">
        <title>Create Game</title>
    </head>
    <body>
    <div>
        <h1>Create game</h1>
        @using (Html.BeginForm("CreateGame", "Game"))
        {
            @Html.LabelFor(x => x.Player1)<br/>
            @Html.TextBoxFor(x => x.Player1)<br/>
            @Html.LabelFor(x => x.Player2)<br/>
            @Html.TextBoxFor(x => x.Player2)<br/><br/>

            <input id="btnSave" type="submit" value="Spara"/>



        }
    </div>
        <div>
            <h1>Set winner</h1>
            @using (Html.BeginForm("SetWinner", "Game"))
            {

            <label>Player</label><br/>
                <input type="text" name="player" id="player"/><br/>
                <label>Game ID</label><br />
             <input type="text" name="gameId" id="gameId" /><br /><br />

                <input id="btnSave" type="submit" value="Spara" />



            }
        </div>
    </body>
    </html>
}

src/CouronneAPI/Views/Player/Index.cshtml
@model CouronneAPI.Models.Player
@{
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head id="Head1">
        <title>Create Player</title>
    </head>
    <body>
    <div>
        <h1>Create player</h1>
        @using (Html.BeginForm("CreatePlayer", "Player"))
        {
            @Html.LabelFor(x => x.UserName)<br />
            @Html.TextBoxFor(x => x.UserName)<br />
            @Html.LabelFor(x => x.FirstName)<br/>
            @Html.TextBoxFor(x => x.FirstName)<br/>
            @Html.LabelFor(x => x.LastName)<br/>
            @Html.TextBoxFor(x => x.LastName)<br/><br/>

            <input id="btnSave" type="submit" value="Spara"/>



        }
  
    </body>
    </html>
}